name: Deploy Pixelator Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package Lambda code
        run: |
          zip -r lambda.zip lambda_function.py

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name pixelator \
            --zip-file fileb://lambda.zip

      - name: Update Lambda environment variable for processed bucket
        run: |
          aws lambda update-function-configuration \
            --function-name pixelator \
            --environment "Variables={PROCESSED_BUCKET=pixelator-35010-prrocessed}"
