name: Deploy Pixelator Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir lambda_package
          pip install -r requirements.txt -t lambda_package

      - name: Copy Lambda function
        run: cp lambda_function.py lambda_package/

      - name: Zip Lambda package
        run: |
          cd lambda_package
          zip -r ../lambda.zip .
          cd ..

      - name: Deploy Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws lambda update-function-code \
            --function-name pixelator \
            --zip-file fileb://lambda.zip \
            --region us-east-1

      - name: Wait for Lambda update to finish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws lambda wait function-updated --function-name pixelator --region us-east-1

      - name: Update Lambda environment variable for processed bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws lambda update-function-configuration \
            --function-name pixelator \
            --region us-east-1 \
            --environment "Variables={processed_bucket=pixelator-35010-processed}"